# Generated by Django 3.1.4 on 2020-12-09 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_comment',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 8, 32, 21, 118604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 8, 32, 21, 118263, tzinfo=utc)),
        ),
    ]
